server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbgirl
    username: test
    password: yygucailiang
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


